import React,{useEffect,useState}from'react';import{createRoot}from'react-dom/client';import{Waves,Clock3,CalendarDays,Map,Menu}from'lucide-react';import'./style.css';
const API='https://estoa-api.onrender.com';
const localISO=d=>new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,19);
const phase=p=>p==='EBB'?'REFLUJO':p==='FLOOD'?'FLUJO':p==='SLACK'?'ESTOA':p??'—';
function Conditions({data,label}){let c=data?.current,t=data?.tide;return <><section className="hero"><span>{label}</span><h1>{c?.intensity_kn??'—'} <i>kn</i></h1><h2>{phase(c?.phase)}</h2><p>{c?.direction_true!=null?Math.round(c.direction_true)+'° verdadero':'Dirección no disponible'} {c?.trend==='DECREASING'?'· disminuyendo':c?.trend==='INCREASING'?'· aumentando':''}</p></section><div className="grid"><article><span>MAREA</span><strong>{t?.height_m!=null?Number(t.height_m).toFixed(2)+' m':'—'}</strong><p>{t?.trend??t?.state??'Según disponibilidad'}</p></article><article><span>FUENTE</span><strong>PUB 3015</strong><p>Predicción astronómica 2026</p></article></div></>}
function App(){const[stations,setStations]=useState([]),[sid,setSid]=useState('CUR011'),[data,setData]=useState(null),[tab,setTab]=useState('Ahora'),[future,setFuture]=useState([]),[moment,setMoment]=useState(localISO(new Date()).slice(0,16)),[momentData,setMomentData]=useState(null);
useEffect(()=>{fetch(API+'/stations').then(r=>r.json()).then(setStations)},[]);
useEffect(()=>{if(tab!=='Ahora')return;fetch(API+'/conditions/at?station_id='+sid+'&local_datetime='+localISO(new Date())).then(r=>r.json()).then(setData)},[sid,tab]);
useEffect(()=>{if(tab!=='Próximamente')return;fetch(API+'/forecast?station_id='+sid+'&start='+localISO(new Date())+'&hours=48').then(r=>r.json()).then(x=>setFuture(x.events||[]))},[sid,tab]);
const queryMoment=()=>fetch(API+'/conditions/at?station_id='+sid+'&local_datetime='+moment+':00').then(r=>r.json()).then(setMomentData);
return <main><header><div><b>ESTOA</b><small>CORRIENTES Y MAREAS · PATAGONIA CHILE</small></div><select value={sid} onChange={e=>setSid(e.target.value)}>{stations.map(s=><option key={s.station_id} value={s.station_id}>{s.station_name}</option>)}</select></header>
{tab==='Ahora'&&<Conditions data={data} label="CONDICIÓN ACTUAL"/>}
{tab==='Próximamente'&&<section className="page"><span>PRÓXIMAS 48 HORAS</span><h3>Eventos de corriente</h3>{future.length?future.map((e,i)=><article className="event" key={i}><div><b>{new Date(e.local_datetime).toLocaleString('es-CL',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}</b><small>{phase(e.event_type==='MAX_EBB'?'EBB':e.event_type==='MAX_FLOOD'?'FLOOD':e.event_type==='SLACK'?'SLACK':e.event_type)}</small></div><strong>{e.intensity_kn!=null?e.intensity_kn+' kn':'—'}</strong></article>):<p>Cargando predicción…</p>}</section>}
{tab==='Momento'&&<section className="page"><span>CONSULTAR UN MOMENTO</span><h3>Fecha y hora</h3><input className="datetime" type="datetime-local" value={moment} onChange={e=>setMoment(e.target.value)}/><button className="primary" onClick={queryMoment}>Calcular condiciones</button>{momentData&&<Conditions data={momentData} label="CONDICIÓN CALCULADA"/>}</section>}
{tab==='Mapa'&&<section className="page"><span>MAPA</span><h3>22 puntos ESTOA</h3><p>La selección geográfica y sugerencia por GPS será el siguiente módulo.</p></section>}
{tab==='Más'&&<section className="page"><span>ESTOA</span><h3>Corrientes y Mareas</h3><p>Predicciones hidrográficas basadas en la edición 2026. La astronomía se utiliza como contexto y no modifica la intensidad calculada.</p><div className="note">Las condiciones meteorológicas y oceanográficas reales pueden producir diferencias respecto de las predicciones astronómicas.</div></section>}
{tab!=='Más'&&tab!=='Mapa'&&<section className="note">ESTOA presenta predicciones hidrográficas. Las condiciones reales pueden diferir de las predicciones publicadas.</section>}
<nav>{[[Waves,'Ahora'],[Clock3,'Próximamente'],[CalendarDays,'Momento'],[Map,'Mapa'],[Menu,'Más']].map(([I,n])=><button className={tab===n?'on':''} onClick={()=>setTab(n)} key={n}><I size={21}/><small>{n}</small></button>)}</nav></main>}
createRoot(document.getElementById('root')).render(<App/>);