import React,{useEffect,useState}from'react';import{createRoot}from'react-dom/client';import{Waves,Clock3,CalendarDays,Map,Menu,MapPin,LocateFixed}from'lucide-react';import'./style.css';
const API='https://estoa-api.onrender.com';
const localISO=d=>new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,19);
const phase=p=>p==='EBB'?'REFLUJO':p==='FLOOD'?'FLUJO':p==='SLACK'?'ESTOA':p??'—';
function Conditions({data,label}){let c=data?.current,t=data?.tide;return <><section className="hero"><span>{label}</span><h1>{c?.intensity_kn??'—'} <i>kn</i></h1><h2>{phase(c?.phase)}</h2><p>{c?.direction_true!=null?Math.round(c.direction_true)+'° verdadero':'Dirección no disponible'} {c?.trend==='DECREASING'?'· disminuyendo':c?.trend==='INCREASING'?'· aumentando':''}</p></section><div className="grid"><article><span>MAREA</span><strong>{t?.height_m!=null?Number(t.height_m).toFixed(2)+' m':'—'}</strong><p>{t?.trend??t?.state??'Según disponibilidad'}</p></article><article><span>FUENTE</span><strong>PUB 3015</strong><p>Predicción astronómica 2026</p></article></div></>}
function App(){const[stations,setStations]=useState([]),[sid,setSid]=useState('CUR011'),[data,setData]=useState(null),[tab,setTab]=useState('Ahora'),[future,setFuture]=useState([]),[weak,setWeak]=useState([]),[tides,setTides]=useState([]),[moment,setMoment]=useState(localISO(new Date()).slice(0,16)),[momentData,setMomentData]=useState(null),[nearest,setNearest]=useState(null),[geoMsg,setGeoMsg]=useState('');
useEffect(()=>{fetch(API+'/stations').then(r=>r.json()).then(setStations)},[]);
useEffect(()=>{if(tab!=='Ahora')return;fetch(API+'/conditions/at?station_id='+sid+'&local_datetime='+localISO(new Date())).then(r=>r.json()).then(setData)},[sid,tab]);
useEffect(()=>{if(tab!=='Próximamente')return;let s=localISO(new Date());Promise.all([fetch(API+'/forecast?station_id='+sid+'&start='+s+'&hours=48').then(r=>r.json()),fetch(API+'/weak-windows?station_id='+sid+'&start='+s+'&hours=48&threshold_kn=1').then(r=>r.json()),fetch(API+'/tide-events?station_id='+sid+'&start_local='+s+'&hours=48').then(r=>r.json())]).then(([a,b,c])=>{setFuture(a.events||[]);setWeak(b.windows||[]);setTides(c.events||[])}).catch(()=>{})},[sid,tab]);
const queryMoment=()=>fetch(API+'/conditions/at?station_id='+sid+'&local_datetime='+moment+':00').then(r=>r.json()).then(setMomentData);const rad=x=>x*Math.PI/180;const km=(a,b,c,d)=>{let R=6371,x=rad(c-a),y=rad(d-b),q=Math.sin(x/2)**2+Math.cos(rad(a))*Math.cos(rad(c))*Math.sin(y/2)**2;return 2*R*Math.asin(Math.sqrt(q))};const locate=()=>{setGeoMsg('Solicitando ubicación…');navigator.geolocation.getCurrentPosition(p=>{let best=null;stations.forEach(s=>{if(s.latitude==null||s.longitude==null)return;let d=km(p.coords.latitude,p.coords.longitude,+s.latitude,+s.longitude);if(!best||d<best.d)best={...s,d}});setNearest(best);setGeoMsg(best?'Punto más cercano sugerido':'No hay puntos disponibles')},()=>setGeoMsg('No fue posible obtener tu ubicación'),{enableHighAccuracy:true,timeout:10000})};
return <main><header><div><b>ESTOA</b><small>CORRIENTES Y MAREAS · PATAGONIA CHILE</small></div><select value={sid} onChange={e=>setSid(e.target.value)}>{stations.map(s=><option key={s.station_id} value={s.station_id}>{s.station_name}</option>)}</select></header>
{tab==='Ahora'&&<Conditions data={data} label="CONDICIÓN ACTUAL"/>}
{tab==='Próximamente'&&<section className="page"><span>PRÓXIMAS 48 HORAS</span><h3>Corriente y marea</h3>{weak.length>0&&<div className="weakbox"><b>Ventanas ≤ 1 kn</b>{weak.map((w,i)=><p key={i}>{String(w.start_local??w.start??'').slice(5,16).replace('T',' ')} → {String(w.end_local??w.end??'').slice(5,16).replace('T',' ')}</p>)}</div>}<h4>CORRIENTE</h4>{future.length?future.map((e,i)=><article className="event" key={i}><div><b>{String(e.local_datetime).slice(5,16).replace('T',' ')}</b><small>{phase(e.event_type==='MAX_EBB'?'EBB':e.event_type==='MAX_FLOOD'?'FLOOD':e.event_type==='SLACK'?'SLACK':e.event_type)}</small></div><strong>{e.intensity_kn!=null?e.intensity_kn+' kn':'—'}</strong></article>):<p>Sin eventos disponibles.</p>}<h4>MAREA</h4>{tides.length?tides.map((e,i)=><article className="event tideevent" key={i}><div><b>{String(e.time_local).slice(5,16).replace('T',' ')}</b><small>{e.type==='HW'?'PLEAMAR':e.type==='LW'?'BAJAMAR':e.type}</small></div><strong>{e.height_m!=null?Number(e.height_m).toFixed(2)+' m':'—'}</strong></article>):<p>Este punto no dispone de eventos automáticos de marea para este período.</p>}</section>}
{tab==='Momento'&&<section className="page"><span>CONSULTAR UN MOMENTO</span><h3>Fecha y hora</h3><input className="datetime" type="datetime-local" value={moment} onChange={e=>setMoment(e.target.value)}/><button className="primary" onClick={queryMoment}>Calcular condiciones</button>{momentData&&<Conditions data={momentData} label="CONDICIÓN CALCULADA"/>}</section>}
{tab==='Mapa'&&<section className="page"><span>MAPA DE PUNTOS</span><h3>Estaciones ESTOA</h3><button className="primary locate" onClick={locate}><LocateFixed size={18}/> Sugerir punto por GPS</button>{geoMsg&&<p>{geoMsg}</p>}{nearest&&<article className="suggest"><MapPin/><div><small>SUGERENCIA GPS · {nearest.d.toFixed(1)} km</small><strong>{nearest.station_name}</strong><p>La distancia geográfica no implica equivalencia hidrográfica. Confirma el punto antes de usarlo.</p><button onClick={()=>{setSid(nearest.station_id);setTab('Ahora')}}>Usar este punto</button></div></article>}<div className="stationlist">{stations.map(s=><button key={s.station_id} className={sid===s.station_id?'selected':''} onClick={()=>{setSid(s.station_id);setTab('Ahora')}}><MapPin size={17}/><span><b>{s.station_name}</b><small>{s.station_id} · {s.app_mode?.replaceAll('_',' ')}</small></span></button>)}</div></section>}
{tab==='Más'&&<section className="page"><span>ESTOA</span><h3>Corrientes y Mareas</h3><p>Predicciones hidrográficas basadas en la edición 2026. La astronomía se utiliza como contexto y no modifica la intensidad calculada.</p><div className="note">Las condiciones meteorológicas y oceanográficas reales pueden producir diferencias respecto de las predicciones astronómicas.</div></section>}
{tab!=='Más'&&tab!=='Mapa'&&<section className="note">ESTOA presenta predicciones hidrográficas. Las condiciones reales pueden diferir de las predicciones publicadas.</section>}
<nav>{[[Waves,'Ahora'],[Clock3,'Próximamente'],[CalendarDays,'Momento'],[Map,'Mapa'],[Menu,'Más']].map(([I,n])=><button className={tab===n?'on':''} onClick={()=>setTab(n)} key={n}><I size={21}/><small>{n}</small></button>)}</nav></main>}
createRoot(document.getElementById('root')).render(<App/>);